// Asset builder:  npm run assets
//
// Turns the AI tile sheets into game-ready images:
//   1. removes the painted checkerboard background of every sheet
//   2. cuts out the pieces listed in tools/asset-src/forest.mjs
//   3. scales each one to its "master" size (ISO.TILE_W * ISO.MASTER_SCALE per tile),
//      using high-quality averaging, so at every zoom level the game only shrinks art
//   4. writes assets/tiles/<id>.png and assets/objects/<id>.png
//   5. writes client/data/asset-registry.json - id -> file, size, anchor, collision
//      (map data only ever names ids like "grass_01"; swapping art never touches maps)
//   6. writes tools/out/assets-preview.png - every built asset on one sheet, for checking

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readPng, writePng, createImage } from './lib/png.mjs';
import { removeBackground, findPieces, crop, resize, trim } from './lib/image-ops.mjs';
import { SHEETS } from './asset-src/sheets.mjs';
import forest from './asset-src/forest.mjs';
import { ISO } from '../client/data/iso-config.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MASTER_TILE_W = Math.round(ISO.TILE_W * ISO.MASTER_SCALE);
const SLAB_RATIO = 0.09; // thickness under a flat tile's diamond, as a fraction of its width

const sheetCache = {};
function sheet(name) {
  if (!sheetCache[name]) {
    const clean = removeBackground(readPng(path.join(ROOT, SHEETS[name])));
    sheetCache[name] = { clean, pieces: findPieces(clean) };
  }
  return sheetCache[name];
}

function cutPiece(entry) {
  const s = sheet(entry.sheet);
  if (entry.rect) {
    const [x, y, w, h] = entry.rect;
    return trim(crop(s.clean, x, y, w, h)).image;
  }
  const p = s.pieces[entry.piece];
  if (!p) throw new Error(`${entry.id}: sheet ${entry.sheet} has no piece ${entry.piece}`);
  return trim(crop(s.clean, p.x, p.y, p.w, p.h)).image;
}

function buildTile(entry) {
  const src = cutPiece(entry);
  const scale = MASTER_TILE_W / src.width;
  const image = resize(src, MASTER_TILE_W, Math.max(1, Math.round(src.height * scale)));
  const halfH = MASTER_TILE_W / 4; // half the diamond's height
  let ay;
  if (entry.anchor === 'base') ay = image.height - halfH;                                    // raised block
  else if (entry.anchor === 'slab') ay = image.height - MASTER_TILE_W * SLAB_RATIO - halfH;  // bank sticks up
  else ay = halfH;                                                                           // flat tile
  return { image, ax: MASTER_TILE_W / 2, ay: Math.round(ay) };
}

function buildObject(entry) {
  const src = cutPiece(entry);
  const targetW = Math.round(entry.width * MASTER_TILE_W);
  const scale = targetW / src.width;
  const image = resize(src, targetW, Math.max(1, Math.round(src.height * scale)));
  const ax = Math.round(image.width / 2);
  const ay = entry.anchor === 'center' ? Math.round(image.height / 2) : Math.round(image.height * 0.97);
  return { image, ax, ay, upscale: scale > 1.001 ? +scale.toFixed(2) : 0 };
}

// Parts keep their own proportions; the game stretches them into place (cliff faces, stairs).
function buildPart(entry) {
  const src = cutPiece(entry);
  const targetW = Math.round(entry.width * MASTER_TILE_W);
  const image = resize(src, targetW, Math.max(1, Math.round((src.height * targetW) / src.width)));
  return { image, ax: 0, ay: 0 };
}

const registry = {
  _note: 'Generated by tools/build-assets.mjs - do not edit by hand. Sizes are MASTER pixels (zoom = ISO.MASTER_SCALE).',
  masterScale: ISO.MASTER_SCALE,
  tileW: ISO.TILE_W,
  tileH: ISO.TILE_H,
  assets: {}
};
const built = [];
const t0 = Date.now();

const kinds = [
  ['tile', forest.tiles, 'tiles', buildTile],
  ['object', forest.objects, 'objects', buildObject],
  ['part', forest.parts || [], 'parts', buildPart]
];
for (const [kind, list, dir, build] of kinds) {
  fs.mkdirSync(path.join(ROOT, 'assets', dir), { recursive: true });
  for (const entry of list) {
    const { image, ax, ay, upscale } = build(entry);
    const file = `assets/${dir}/${entry.id}.png`;
    writePng(path.join(ROOT, file), image);
    // flat = lies on the ground (bridges, platforms): always drawn under characters
    const flat = kind === 'object' && entry.anchor === 'center';
    registry.assets[entry.id] = {
      kind, file, w: image.width, h: image.height, ax, ay,
      ...(flat ? { flat: true } : {}),
      ...(entry.collision ? { collision: entry.collision } : {})
    };
    built.push({ id: entry.id, image, upscale });
  }
}

fs.writeFileSync(path.join(ROOT, 'client', 'data', 'asset-registry.json'), `${JSON.stringify(registry, null, 1)}\n`);

// preview sheet: every asset in a row-wrapped grid on a dark background
const pad = 8;
const maxW = 1600;
let x = pad;
let y = pad;
let rowH = 0;
const spots = [];
for (const b of built) {
  if (x + b.image.width + pad > maxW) {
    x = pad;
    y += rowH + pad;
    rowH = 0;
  }
  spots.push({ b, x, y });
  x += b.image.width + pad;
  rowH = Math.max(rowH, b.image.height);
}
const preview = createImage(maxW, y + rowH + pad);
for (let i = 0; i < preview.data.length; i += 4) {
  preview.data[i] = 26;
  preview.data[i + 1] = 22;
  preview.data[i + 2] = 40;
  preview.data[i + 3] = 255;
}
for (const { b, x: px, y: py } of spots) {
  for (let j = 0; j < b.image.height; j++) {
    for (let i = 0; i < b.image.width; i++) {
      const s = (j * b.image.width + i) * 4;
      const a = b.image.data[s + 3] / 255;
      if (!a) continue;
      const d = ((py + j) * preview.width + px + i) * 4;
      for (let c = 0; c < 3; c++) preview.data[d + c] = Math.round(b.image.data[s + c] * a + preview.data[d + c] * (1 - a));
    }
  }
}
fs.mkdirSync(path.join(ROOT, 'tools', 'out'), { recursive: true });
writePng(path.join(ROOT, 'tools', 'out', 'assets-preview.png'), preview);

const upscaled = built.filter((b) => b.upscale);
console.log(`built ${built.length} assets (${forest.tiles.length} tiles, ${forest.objects.length} objects, ${(forest.parts || []).length} parts) in ${Date.now() - t0} ms`);
console.log(`master tile: ${MASTER_TILE_W}x${MASTER_TILE_W / 2} (zoom ${ISO.MASTER_SCALE}); registry -> client/data/asset-registry.json`);
if (upscaled.length) {
  console.log(`note: ${upscaled.length} objects are bigger than their source picture at max zoom (slightly soft):`);
  console.log(`  ${upscaled.map((b) => `${b.id} x${b.upscale}`).join(', ')}`);
}
